name: Deploy Lambda on Merge

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      id-token: write  # GitHub OIDC を使うのに必要
      contents: read  # ソースコードを取得するために必要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true # Bundlerのキャッシュを有効化

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Zip Lambda function
        run: |
          zip -r lambda_function.zip . -x "*.git*"

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name anokumo \
            --zip-file fileb://lambda_function.zip
